services:
  search-setup:
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/frontend/src:/app/src
      - ./apps/frontend/scripts:/app/scripts
  setup:
    environment:
      NODE_ENV: development
  worker:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/frontend/src:/app/src
      - ./apps/frontend/scripts:/app/scripts
      - ./apps/frontend/db:/app/db
  app:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/frontend/src:/app/src
      - ./apps/frontend/scripts:/app/scripts
      - ./apps/frontend/db:/app/db
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]
